#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# O .env.local é o arquivo deste projeto; o padrão da biblioteca é .env.
ENV_FILE=".env.local"

PROD_URL="https://creativehome-gamma.vercel.app"
DEV_PORT="3100"

# console_url PATH [EXTRA] — URL do Console já carimbada com a conta e o
# projeto certos.
#
# Sem `authuser` o Console abre na primeira conta logada no navegador, e sem
# `project` ele abre no último projeto visitado. As duas coisas juntas fazem
# credencial nascer no projeto errado sem nenhum aviso na tela — o erro é
# silencioso e só aparece semanas depois, na verificação.
console_url() {
  local path="$1"
  local project="${2:-}"
  local url="https://console.cloud.google.com${path}?authuser=${AUTHUSER}"
  [[ -n "$project" ]] && url="${url}&project=${project}"
  printf '%s' "$url"
}

# push_vercel KEY VALUE — manda a variável pros três ambientes da Vercel.
# Remove antes de adicionar porque `vercel env add` não sobrescreve: com a
# chave já existente ele falha, e o wizard pararia no meio.
push_vercel() {
  local key="$1" value="$2" env
  command -v vercel >/dev/null 2>&1 || {
    SKIPPED+=("Vercel $key (instale o CLI: npm i -g vercel)")
    warn "Vercel CLI ausente — $key não foi enviada"
    return
  }
  for env in production preview development; do
    vercel env rm "$key" "$env" --yes >/dev/null 2>&1 || true
    printf '%s' "$value" | vercel env add "$key" "$env" >/dev/null 2>&1 || {
      SKIPPED+=("Vercel $key ($env)")
      warn "falhou ao enviar $key para $env"
      return
    }
  done
  printf '  %s✓ Vercel%s %s (production, preview, development)\n' "$GREEN" "$RESET" "$key"
}

banner "Google OAuth — separar Drive e Agenda"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Qual conta do Google"
say "Se você tem mais de uma conta Google logada no navegador, o Console"
say "abre na primeira e ignora qual você queria. O número da conta aparece"
say "como 'authuser=' na barra de endereço do Console."
printf '\n'
step "Abra o Console em qualquer aba e olhe a URL."
note "    ...cloud.google.com/...?authuser=1&project=..."
step "Se não aparecer authuser na URL, responda 0."
printf '\n'
ask AUTHUSER "Número em authuser= (0 é a conta principal):"
AUTHUSER="${AUTHUSER:-0}"
note "Todas as telas daqui pra frente abrem nessa conta."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Projeto novo para a Agenda"
say "A tela de consentimento, os escopos e o status de verificação são do"
say "PROJETO, não do client. Enquanto a Agenda morar no mesmo projeto do"
say "Drive, ela herda o escopo restricted do Drive e a auditoria paga que"
say "vem junto. Por isso: projeto separado."
printf '\n'
open_url "$(console_url /projectcreate)"
step "Nome do projeto: creativehome-agenda"
step "Clique em Criar e espere terminar."
step "Abra o seletor de projetos no topo e copie o ID do projeto novo —"
step "  é o texto embaixo do nome, tipo creativehome-agenda-473912."
printf '\n'
warn "O ID não é o nome: o Google acrescenta números quando o nome já existe."
printf '\n'
ask CALENDAR_PROJECT "Cole o ID do projeto da agenda:"
while [[ -z "$CALENDAR_PROJECT" ]]; do
  warn "Sem o ID as telas seguintes abririam no projeto errado."
  ask CALENDAR_PROJECT "Cole o ID do projeto da agenda:"
done

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Ativar a Google Calendar API"
say "Sem isso o token conecta mas toda chamada volta 403."
printf '\n'
open_url "$(console_url /apis/library/calendar-json.googleapis.com "$CALENDAR_PROJECT")"
step "Confirme no topo que o projeto é ${CALENDAR_PROJECT}."
step "Clique em ATIVAR."
pause "API ativada?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Tela de consentimento da Agenda"
say "Aqui é onde o escopo é declarado. Só calendar — nada de Drive."
printf '\n'
open_url "$(console_url /auth/overview "$CALENDAR_PROJECT")"
step "Tipo de usuário: External."
step "Nome do app: CreativeHome Agenda"
step "E-mail de suporte e e-mail do desenvolvedor: o seu."
step "Em Acesso a dados, clique 'Adicionar ou remover escopos' e marque"
step "  APENAS:"
note "    https://www.googleapis.com/auth/calendar"
step "Em Público-alvo, adicione o Gmail de cada membro como usuário de teste."
printf '\n'
warn "Em modo de teste o refresh token expira em 7 dias: a equipe reconecta"
warn "toda semana até o app ser publicado e verificado pelo Google."
pause "Tela de consentimento salva?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Credenciais da Agenda"
open_url "$(console_url /auth/clients/create "$CALENDAR_PROJECT")"
step "Confirme no topo que o projeto é ${CALENDAR_PROJECT}."
step "Tipo de aplicativo: Aplicativo da Web."
step "Nome: creativehome-agenda-web"
printf '\n'
warn "A tela tem DOIS campos de URL. Deixe 'Origens JavaScript autorizadas'"
warn "VAZIO — ele recusa qualquer endereço com caminho. O app é server-side;"
warn "o navegador nunca chama a API do Google direto."
printf '\n'
step "Role até 'URIs de redirecionamento autorizados' — é o SEGUNDO bloco."
step "Clique em + ADICIONAR URI e cole uma em cada linha:"
note "    http://localhost:${DEV_PORT}/api/calendar/oauth/callback"
note "    ${PROD_URL}/api/calendar/oauth/callback"
step "Clique em Criar. Os dois valores aparecem na janela que abrir."
printf '\n'
ask        GOOGLE_CALENDAR_CLIENT_ID     "Cole o ID do cliente:"
ask_secret GOOGLE_CALENDAR_CLIENT_SECRET "Cole a Chave secreta do cliente:"
write_env  GOOGLE_CALENDAR_CLIENT_ID     "$GOOGLE_CALENDAR_CLIENT_ID"
write_env  GOOGLE_CALENDAR_CLIENT_SECRET "$GOOGLE_CALENDAR_CLIENT_SECRET"
write_env  GOOGLE_CALENDAR_REDIRECT_URI  "http://localhost:${DEV_PORT}/api/calendar/oauth/callback"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Projeto antigo — o Drive"
say "O projeto original volta a ser só do Drive: uma conta, a do estúdio."
printf '\n'
ask DRIVE_PROJECT "ID do projeto do Drive (o antigo):"
open_url "$(console_url /auth/clients "$DRIVE_PROJECT")"
step "Confirme no topo que o projeto é o do Drive."
step "Na tela de consentimento, remova o escopo de calendar se estiver"
step "  listado — nenhum código usa mais o token do estúdio pra agenda."
step "Abra o client OAuth existente e confirme as URIs de redirecionamento:"
note "    http://localhost:${DEV_PORT}/api/drive/oauth/callback"
note "    ${PROD_URL}/api/drive/oauth/callback"
step "Copie o ID e a chave secreta desse client."
printf '\n'
ask        GOOGLE_DRIVE_CLIENT_ID     "Cole o ID do cliente do Drive:"
ask_secret GOOGLE_DRIVE_CLIENT_SECRET "Cole a Chave secreta do Drive:"
write_env  GOOGLE_DRIVE_CLIENT_ID     "$GOOGLE_DRIVE_CLIENT_ID"
write_env  GOOGLE_DRIVE_CLIENT_SECRET "$GOOGLE_DRIVE_CLIENT_SECRET"
write_env  GOOGLE_DRIVE_REDIRECT_URI  "http://localhost:${DEV_PORT}/api/drive/oauth/callback"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Produção na Vercel"
say "Mesmas credenciais, URIs apontando para o domínio publicado."
note "  $PROD_URL"
printf '\n'
if confirm "Enviar as 6 variáveis para a Vercel agora?"; then
  push_vercel GOOGLE_CALENDAR_CLIENT_ID     "$GOOGLE_CALENDAR_CLIENT_ID"
  push_vercel GOOGLE_CALENDAR_CLIENT_SECRET "$GOOGLE_CALENDAR_CLIENT_SECRET"
  push_vercel GOOGLE_CALENDAR_REDIRECT_URI  "${PROD_URL}/api/calendar/oauth/callback"
  push_vercel GOOGLE_DRIVE_CLIENT_ID        "$GOOGLE_DRIVE_CLIENT_ID"
  push_vercel GOOGLE_DRIVE_CLIENT_SECRET    "$GOOGLE_DRIVE_CLIENT_SECRET"
  push_vercel GOOGLE_DRIVE_REDIRECT_URI     "${PROD_URL}/api/drive/oauth/callback"
  printf '\n'
  note "As variáveis só valem no próximo deploy: rode 'vercel --prod'."
else
  SKIPPED+=("Vercel: as 6 variáveis GOOGLE_* ainda não foram enviadas")
fi

finish
say "Para testar agora:"
note "  npx next dev -p ${DEV_PORT}"
note "  abra http://localhost:${DEV_PORT}/admin/agenda e clique em Conectar"
printf '\n'
